### ISSUE TITLE
Wrong image in series

### ISSUE THREAD

**Issue by raspopov** [dogpixels/patreon-helper#1]
The some images in series gets correct name but content of the another image i.e. duped.

Looks like that affects a neighbor images.

P.S. Wonderful extension!

**Comment by dogpixels** [comment]
Hello raspopov, thanks for your bug report. I've added a new feature enabling you to share an extensive log that will hopefully help me narrow down where the issue occurs. Please do the following:

 * In Firefox' addon settings > _Patreon Helper_ > _Options_, enable the new _Enable Logging_ option.
 * Browse Patreon on a page containing an affected post that causes the bug to occur.
 * Back to the options page, click _copy to clipboard_ to copy the entire log.
 * Paste the log into a text file.
 * Send the log file to draconigen@gmail.com along with a pointer to which files cause the issue.

I'll then have a chance to narrow down where this bug comes from.
Cheers!

**Comment by dogpixels** [comment]
No further problems reported, the issue seems to be resolved. Feel free to reopen if similiar issues occur!
